"""Tests for email formatter utility."""

from ai_code_reviewer.api.core.email_formatter import format_review_to_html


def test_format_simple_markdown():
    """Test basic markdown to HTML conversion."""
    markdown_text = """# Test Review

## Summary
This is a test review with **bold** text and `code`.

## Issues Found
- Bug 1
- Bug 2
"""
    html = format_review_to_html(markdown_text)

    # Check that basic HTML structure is present
    assert "<!DOCTYPE html>" in html
    assert "<html>" in html
    assert "<body>" in html

    # Check that markdown was converted
    assert "<h1>" in html and "Test Review" in html
    assert "<h2>" in html and "Summary" in html
    assert "<strong>bold</strong>" in html
    assert "<code>code</code>" in html
    assert "<li>Bug 1</li>" in html
    assert "<li>Bug 2</li>" in html


def test_format_code_blocks():
    """Test code block conversion."""
    markdown_text = """# Code Review

Here's some code:

```python
def hello():
    print("world")
```
"""
    html = format_review_to_html(markdown_text)

    # Check that code block is converted
    assert "<pre>" in html
    assert "<code" in html
    assert "def hello():" in html


def test_format_with_styling():
    """Test that CSS styling is included."""
    markdown_text = "# Test"
    html = format_review_to_html(markdown_text)

    # Check that styling is present
    assert "<style>" in html
    assert "font-family" in html
    assert "color:" in html
    assert ".content" in html


def test_format_with_footer():
    """Test that footer is included."""
    markdown_text = "# Test"
    html = format_review_to_html(markdown_text)

    # Check that footer is present
    assert "This review was generated by AI Code Reviewer" in html
    assert "🤖" in html


def test_format_empty_text():
    """Test handling of empty text."""
    html = format_review_to_html("")

    # Should still return valid HTML structure
    assert "<!DOCTYPE html>" in html
    assert "<html>" in html


def test_format_with_lists():
    """Test ordered and unordered lists."""
    markdown_text = """# Lists Test

Unordered list:

- Item 1
- Item 2

Ordered list:

1. First
2. Second
"""
    html = format_review_to_html(markdown_text)

    # Check that lists are converted (they should have <li> tags)
    assert "<li>" in html
    assert "Item 1" in html
    assert "First" in html


def test_format_with_inline_formatting():
    """Test inline formatting (bold, italic, code)."""
    markdown_text = "This has **bold**, *italic*, and `code` text."
    html = format_review_to_html(markdown_text)

    assert "<strong>bold</strong>" in html
    assert "<em>italic</em>" in html
    assert "<code>code</code>" in html


def test_format_guidelines_violations():
    """Test formatting a typical review with guidelines violations."""
    markdown_text = """# 🤖 AI Code Review

## Concise Conclusion
The code has 2 guideline violations that must be addressed.

## Recommended Changes
- Fix async/await usage
- Add type hints

## Potential Issues Found:

**Bugs**
No issues found.

**Performance**
No issues found.

**Security**
No issues found.

**Coding Guidelines Violations**
- Violates Python Rule #1: Type Hints - Missing type annotations on function parameters
- Violates Python Rule #3: Async/Await for I/O - Using synchronous I/O operation

## Recommended Best Practices
All is good, no suggestion.
"""
    html = format_review_to_html(markdown_text)

    # Check that all sections are present
    assert "🤖 AI Code Review" in html
    assert "Concise Conclusion" in html
    assert "Coding Guidelines Violations" in html
    assert "Python Rule #1" in html
    assert "Type Hints" in html
    assert "<strong>" in html  # Bold formatting
    assert "<li>" in html  # List items
